### PR TITLE
comment out CORS config for jetty, only one of tomcat or jetty should be enabled

### PR DESCRIPTION
**Pull request by landryb**
should fix georchestra/georchestra#3358 - need submodule update for branches `master` & `20.1.x` ofc.

### CODE REVIEW

**Comment by jeanpommier** [comment]
I would rather have both blocks commented by default. And uncomment the proper one on deploy (Ansible, Docker). This would ensure that the war file we produce is properly working, whatever the servlet server

I agree that a solution that only works on docker sucks. The opposite does too. At least conceptually.

**Comment by pmauduit** [comment]
> I would rather have both blocks commented by default. And uncomment the proper one on deploy (Ansible, Docker). This would ensure that the war file we produce is properly working, whatever the servlet server
> 
> I agree that a solution that only works on docker sucks. The opposite does too. At least conceptually.

That was also my point, but it didn't make consensus, see comments on the linked issue

**Comment by landryb** [comment]
docker doesnt use this web.xml so its unaffected, and 99% of non-docker deployments (be it via ansible or not, totally unrelated) are done on tomcat because that's what's in the doc.

**Comment by jeanpommier** [comment]
Yep, but what about the 1% that might want to use jetty (wihtout docker), or glassfish or whatever ? They might really have a hard time to figure it out
Can't it be uncommented/replaced in the Ansible playbook, like it is done in docker config ?
It would also mean less custom changes from geoserver upstream when we upgrade the geoserver version

**Comment by landryb** [comment]
>  It would also mean less custom changes from geoserver upstream when we upgrade the geoserver version

you mean like commits blindly applying all georchestra changes in jumbo patches like georchestra/geoserver@9b1e38b and georchestra/geoserver@b67db20 (i know, cherrypicking/applying each atomic patch one by one is much more work, but keeps logic/history clearer..), and thus leading to the breakage we have now for everyone not using docker ? :)

> Yep, but what about the 1% that might want to use jetty (wihtout docker), or glassfish or whatever ? They might really have a hard time to figure it out

then they'll come to the lists and we'll direct them to the doc someone might write someday about CORS ? afaict, we want CORS working by default in the general setup, which is tomcat (cf https://github.com/georchestra/georchestra/issues/3358#issuecomment-837955744), whether its deployed/configured manually or via ansible.

**Comment by jeanpommier** [comment]
Wow, that was harsh. I was just applying the same modus operandi than on previous branches. I did not know it was already broken on some configs and pending a fix. How come, BTW, that we can't define issues on this repo ?

OK, let's do it your way, no pb for me (i'm using docker, anyway ;o)

**Comment by landryb** [comment]
> Wow, that was harsh. I was just applying the same modus operandi than on previous branches. I did not know it was already broken on some configs and pending a fix. 

oh, it's just known broken since a year or so .. https://github.com/georchestra/georchestra/pull/3094#issuecomment-653018614 i only got fed up with it and filed georchestra/georchestra#3358 a month ago, so technically, you couldnt know.. i'm not blaming anyone, just being fed up by the docker setup deviating from the middleware docs (thus docs tend to get unmaintained) and the lack of testing on non-docker cases.

> How come, BTW, that we can't define issues on this repo ?

i think no issues because it's a fork of the geoserver repo..

> OK, let's do it your way, no pb for me (i'm using docker, anyway ;o)

I suppose so, devs use docker so test this usecase only, ops like me dont use it so gets to fix the broken pieces because nobody gets paid to fix the non-docker case :) the wonderful world of """devops"""..

**Comment by jeanpommier** [comment]
Shoudln't we merge this one ?

**Comment by fvanderbiest** [comment]
> nobody gets paid to fix the non-docker case

@landryb I think you are ;-)
Joking.

**Pull request merged**
