### PR TITLE
Remove useless warning about 'anonymous' user not found

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Review by pmauduit — APPROVED** [review]
It should fit with geOrchestra conventions, but I've some questions: how are you sure that the user is "anonymous" in our case ? Could it be something else ? Could it be null ?

**Comment by Vampouille** [comment]
> It should fit with geOrchestra conventions, but I've some questions: how are you sure that the user is "anonymous" in our case ? Could it be something else ? Could it be null ?

During my tests, every call to `existsUser()` method is done with "anonymous" as argument. So this PR should remove most of unwanted logs.

But you're right, maybe I can switch test order to avoid NPE when null is passed.

**Comment by Vampouille** [comment]
> But you're right, maybe I can switch test order to avoid NPE when null is passed.

Last commit 3a1b057 fix this

**Comment by jusabatier** [comment]
It can be a more clean way to treat this problem as it solve also performance problem with anonymous users : https://github.com/georchestra/geoserver/pull/12

**Comment by pmauduit** [comment]
I'm ok with @jusabatier's proposal, but PR #12 is missing the customization present in this PR. Ping @Vampouille

**Comment by jusabatier** [comment]
I tested PR #12 (for geofence perf), it increase the treatment speed of anonymous requests.

Unfortunately, I noticed that perfs for logged users are also increased dramatically and result in a 504 error...

**Pull request closed without merging**
